//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uyg_vz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cevap
    {
        public string cevapId { get; set; }
        public string cevapSecenekId { get; set; }
        public string cevapSecenek { get; set; }
        public string cevapUyeId { get; set; }
        public System.DateTime cevaplamaZamani { get; set; }
    
        public virtual Secenek Secenek { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
